/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "awsbuildonApi",
            "endpoint": "https://w5nrsu3fhk.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:67d42571-d506-42e5-9376-cb3255221f9e",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_uqQDw8uBJ",
    "aws_user_pools_web_client_id": "2psfbpktqi82h8abvanqrc3kip",
    "oauth": {},
    "predictions": {
        "interpret": {
            "interpretText": {
                "region": "ap-southeast-1",
                "proxy": false,
                "defaults": {
                    "type": "SENTIMENT"
                }
            }
        }
    }
};


export default awsmobile;
